/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { StoryHuntV3PoolDeployer } from "../StoryHuntV3PoolDeployer";

export class StoryHuntV3PoolDeployer__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<StoryHuntV3PoolDeployer> {
    return super.deploy(overrides || {}) as Promise<StoryHuntV3PoolDeployer>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): StoryHuntV3PoolDeployer {
    return super.attach(address) as StoryHuntV3PoolDeployer;
  }
  connect(signer: Signer): StoryHuntV3PoolDeployer__factory {
    return super.connect(signer) as StoryHuntV3PoolDeployer__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): StoryHuntV3PoolDeployer {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as StoryHuntV3PoolDeployer;
  }
}

const _abi = [
  {
    inputs: [],
    name: "parameters",
    outputs: [
      {
        internalType: "address",
        name: "factory",
        type: "address",
      },
      {
        internalType: "address",
        name: "token0",
        type: "address",
      },
      {
        internalType: "address",
        name: "token1",
        type: "address",
      },
      {
        internalType: "uint24",
        name: "fee",
        type: "uint24",
      },
      {
        internalType: "int24",
        name: "tickSpacing",
        type: "int24",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060b88061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80638903573014602d575b600080fd5b60336075565b604080516001600160a01b0396871681529486166020860152929094168383015262ffffff16606083015260029290920b608082015290519081900360a00190f35b600054600154600280546001600160a01b03938416939283169281169162ffffff600160a01b83041691600160b81b9004900b8556fea164736f6c6343000706000a";
